live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.normal]
black = "#242424"
blue = "#18a9c7"
cyan = "#7ec589"
green = "#6eaa76"
magenta = "#D16D9E"
# orange = "#d19a66"
# purple = "#ad7fa8"
red = "#f15d22"
white = "#D8DEE9"
yellow = "#eece61"

[colors.primary]
background = "#222222"
foreground = "#cccccc"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|: \"' ()[]{}<>"

[window.dimensions]
columns = 100
lines = 26

[window.padding]
x = 0
y = 0
